-- MySQL Script generated by MySQL Workbench
-- Sat Oct 31 22:39:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema baber
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baber
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baber` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `baber` ;

-- -----------------------------------------------------
-- Table `baber`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baber`.`appointment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `combo_id` INT(11) NOT NULL,
  `date` DATETIME NOT NULL,
  `message` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `name_stylist` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `time` VARCHAR(255) NOT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8tdc87a9b86kwmy80fiwo4ybc` (`combo_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `baber`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baber`.`bill` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `appointment_id` INT(11) NOT NULL,
  `combo_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `customer` VARCHAR(255) NOT NULL,
  `note` VARCHAR(300) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `status` INT(11) NULL DEFAULT '0',
  `total` DOUBLE NULL DEFAULT '0',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKsixmr31g7vbs03rvq35g8x4b5` (`appointment_id` ASC) VISIBLE,
  INDEX `FKny7sqflypbfg7c36guxxh0ju7` (`combo_id` ASC) VISIBLE,
  INDEX `FKs78seu7p3wfrnuhulmtpg707u` (`user_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `baber`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baber`.`blog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `description` VARCHAR(300) NOT NULL,
  `img_blog` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `status` INT(11) NULL DEFAULT '0',
  `title` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `baber`.`combo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baber`.`combo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` INT(11) NOT NULL,
  `step1` VARCHAR(255) NOT NULL,
  `step2` VARCHAR(255) NOT NULL,
  `step3` VARCHAR(255) NOT NULL,
  `step4` VARCHAR(255) NULL DEFAULT NULL,
  `step5` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `baber`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baber`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `baber`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baber`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKp56c1712k691lhsyewcssf40f` (`role_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `baber`;

DELIMITER $$
USE `baber`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `baber`.`delete_bill_table`
AFTER DELETE ON `baber`.`appointment`
FOR EACH ROW
BEGIN
DECLARE v_appointment_id INTEGER;
set v_appointment_id = old.id;

delete from bill where appointment_id = v_appointment_id;
END$$

USE `baber`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `baber`.`insert_to_bill_table`
AFTER INSERT ON `baber`.`appointment`
FOR EACH ROW
BEGIN
DECLARE combo_id INTEGER;
DECLARE user_id INTEGER;
DECLARE appointment_id INTEGER;
DECLARE customer char(255);
DECLARE phone char(10);
SET combo_id = New.combo_id;
SET user_id = NEW.id_user;
SET appointment_id = New.id;
SET customer = new.name;
SET phone = new.phone;
INSERT INTO bill (combo_id,user_id,appointment_id,customer,phone)VALUES (combo_id,user_id,appointment_id,customer,phone);
END$$

USE `baber`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `baber`.`update_to_bill_table`
AFTER UPDATE ON `baber`.`appointment`
FOR EACH ROW
BEGIN
DECLARE v_user_id INTEGER;
DECLARE v_appointment_id INTEGER;
set v_user_id = new.id_user;
set v_appointment_id = (select app.id from appointment app inner join bill b on app.id = b.appointment_id );

update bill set user_id = v_user_id where appointment_id = v_appointment_id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
